#!/usr/bin/env bash

packages=(
  .
  packages/project-eden-types
  packages/project-eden-cms
  packages/project-eden-ui
  packages/project-eden-app
)

for i in "${packages[@]}"
do
  if test -f "$i/.tmuxinator.yml"; then
    echo "Loading $i/.tmuxinator.yml"
    $(cd "$i" && tmuxinator start)
  fi
done
